// <auto-generated />
using InheritanceExample;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace InheritanceExample.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InheritanceExample.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("KilledByHunterId");

                    b.Property<string>("Name");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("KilledByHunterId");

                    b.ToTable("Animals");

                    b.HasDiscriminator<string>("Type").HasValue("Animal");
                });

            modelBuilder.Entity("InheritanceExample.Entities.Hunter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Hunters");
                });

            modelBuilder.Entity("InheritanceExample.Entities.Eagle", b =>
                {
                    b.HasBaseType("InheritanceExample.Entities.Animal");

                    b.Property<decimal>("HuntDistance");

                    b.ToTable("Eagle");

                    b.HasDiscriminator().HasValue("eagle");
                });

            modelBuilder.Entity("InheritanceExample.Entities.Fox", b =>
                {
                    b.HasBaseType("InheritanceExample.Entities.Animal");

                    b.Property<int>("ChickenKilled");

                    b.Property<int>("LegCount")
                        .HasColumnName("LegCount");

                    b.ToTable("Fox");

                    b.HasDiscriminator().HasValue("fox");
                });

            modelBuilder.Entity("InheritanceExample.Entities.Wolf", b =>
                {
                    b.HasBaseType("InheritanceExample.Entities.Animal");

                    b.Property<int>("LegCount")
                        .HasColumnName("LegCount");

                    b.Property<int>("SheepKilled");

                    b.ToTable("Wolf");

                    b.HasDiscriminator().HasValue("wolf");
                });

            modelBuilder.Entity("InheritanceExample.Entities.Animal", b =>
                {
                    b.HasOne("InheritanceExample.Entities.Hunter", "KilledByHunter")
                        .WithMany("KilledAnimals")
                        .HasForeignKey("KilledByHunterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
